import type {
  Client,
  DesignReview,
  Invoice,
  Person,
  Project,
} from "@/lib/types";

export const team: Person[] = [
  {
    id: "u1",
    name: "Maya Chen",
    email: "maya@agency.os",
    role: "owner",
    avatarColor: "from-violet-500 to-fuchsia-500",
    utilization: 72,
    capacity: 40,
  },
  {
    id: "u2",
    name: "Diego Alvarez",
    email: "diego@agency.os",
    role: "pm",
    avatarColor: "from-sky-500 to-cyan-400",
    utilization: 88,
    capacity: 40,
  },
  {
    id: "u3",
    name: "Priya Shah",
    email: "priya@agency.os",
    role: "designer",
    avatarColor: "from-amber-500 to-pink-500",
    utilization: 94,
    capacity: 40,
  },
  {
    id: "u4",
    name: "Jonas Weber",
    email: "jonas@agency.os",
    role: "engineer",
    avatarColor: "from-emerald-500 to-teal-500",
    utilization: 81,
    capacity: 40,
  },
  {
    id: "u5",
    name: "Aiko Tanaka",
    email: "aiko@agency.os",
    role: "engineer",
    avatarColor: "from-rose-500 to-orange-400",
    utilization: 68,
    capacity: 40,
  },
  {
    id: "u6",
    name: "Sam Okafor",
    email: "sam@agency.os",
    role: "qa",
    avatarColor: "from-indigo-500 to-blue-500",
    utilization: 55,
    capacity: 40,
  },
  {
    id: "u7",
    name: "Lila Martin",
    email: "lila@agency.os",
    role: "finance",
    avatarColor: "from-lime-500 to-emerald-500",
    utilization: 45,
    capacity: 40,
  },
];

export const personById = (id: string) =>
  team.find((p) => p.id === id) ?? {
    id,
    name: "Unknown",
    email: "",
    role: "client" as const,
    avatarColor: "from-zinc-400 to-zinc-600",
  };

export const clients: Client[] = [
  {
    id: "c1",
    name: "Northwind Coffee",
    industry: "Hospitality",
    primaryContact: "Renee Park",
    email: "renee@northwind.co",
    stage: "won",
    arr: 168000,
    health: "green",
    lastTouch: "2 days ago",
    logoColor: "from-amber-600 to-orange-700",
  },
  {
    id: "c2",
    name: "Helio Health",
    industry: "Healthcare",
    primaryContact: "Dr. Adam Field",
    email: "adam@heliohealth.com",
    stage: "won",
    arr: 312000,
    health: "yellow",
    lastTouch: "5 hours ago",
    logoColor: "from-emerald-500 to-teal-600",
  },
  {
    id: "c3",
    name: "Atlas Logistics",
    industry: "Logistics",
    primaryContact: "Theo Kane",
    email: "theo@atlaslog.io",
    stage: "negotiation",
    arr: 0,
    health: "yellow",
    lastTouch: "yesterday",
    logoColor: "from-slate-600 to-slate-800",
  },
  {
    id: "c4",
    name: "Lumen Studios",
    industry: "Media",
    primaryContact: "Mei Watanabe",
    email: "mei@lumen.studio",
    stage: "proposal",
    arr: 0,
    health: "green",
    lastTouch: "today",
    logoColor: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "c5",
    name: "Beacon Finance",
    industry: "Fintech",
    primaryContact: "Ravi Krishnan",
    email: "ravi@beaconfin.com",
    stage: "qualified",
    arr: 0,
    health: "green",
    lastTouch: "3 days ago",
    logoColor: "from-blue-600 to-indigo-700",
  },
  {
    id: "c6",
    name: "Verdant Goods",
    industry: "Retail / D2C",
    primaryContact: "Selma Reyes",
    email: "selma@verdant.shop",
    stage: "new",
    arr: 0,
    health: "green",
    lastTouch: "1 week ago",
    logoColor: "from-green-600 to-emerald-700",
  },
  {
    id: "c7",
    name: "Civica Public",
    industry: "Public Sector",
    primaryContact: "Owen Hart",
    email: "owen@civica.gov",
    stage: "won",
    arr: 96000,
    health: "red",
    lastTouch: "12 days ago",
    logoColor: "from-red-600 to-rose-700",
  },
];

export const clientById = (id: string) => clients.find((c) => c.id === id);

export const projects: Project[] = [
  {
    id: "p1",
    name: "Northwind — D2C Rebrand",
    clientId: "c1",
    status: "design",
    startDate: "2026-03-04",
    targetDate: "2026-06-12",
    progress: 42,
    budget: 145000,
    spent: 64200,
    margin: 31,
    team: ["u2", "u3", "u4"],
    pm: "u2",
    description:
      "Full rebrand rollout: identity, marketing site, and Shopify storefront with packaging touchpoints.",
    scopeCreepPct: 3.4,
    onTime: true,
    milestones: [
      {
        id: "m1",
        name: "Brand Direction Locked",
        dueDate: "2026-04-02",
        amount: 28000,
        paid: true,
      },
      {
        id: "m2",
        name: "Site Design Approved",
        dueDate: "2026-05-09",
        amount: 42000,
        paid: false,
      },
      {
        id: "m3",
        name: "Storefront Launch",
        dueDate: "2026-06-12",
        amount: 75000,
        paid: false,
      },
    ],
    tasks: [
      {
        id: "t1",
        title: "Refine logo lockup variations",
        status: "in_review",
        assignee: "u3",
        priority: "high",
        estimateHours: 12,
        loggedHours: 9,
      },
      {
        id: "t2",
        title: "Build PDP component in Storybook",
        status: "in_progress",
        assignee: "u4",
        priority: "high",
        estimateHours: 16,
        loggedHours: 6,
      },
      {
        id: "t3",
        title: "Color system tokens for Tailwind",
        status: "done",
        assignee: "u3",
        priority: "medium",
        estimateHours: 6,
        loggedHours: 5,
      },
      {
        id: "t4",
        title: "Photography shot list",
        status: "backlog",
        assignee: "u2",
        priority: "low",
        estimateHours: 4,
        loggedHours: 0,
      },
      {
        id: "t5",
        title: "Migrate legacy SKUs to Shopify",
        status: "backlog",
        assignee: "u4",
        priority: "medium",
        estimateHours: 24,
        loggedHours: 0,
      },
    ],
  },
  {
    id: "p2",
    name: "Helio — Patient Portal v2",
    clientId: "c2",
    status: "build",
    startDate: "2026-01-15",
    targetDate: "2026-05-30",
    progress: 71,
    budget: 285000,
    spent: 211400,
    margin: 22,
    team: ["u2", "u4", "u5", "u6"],
    pm: "u2",
    description:
      "HIPAA-compliant patient portal: appointments, telehealth, secure messaging, and lab results.",
    scopeCreepPct: 6.1,
    onTime: false,
    milestones: [
      {
        id: "m4",
        name: "Discovery & Compliance Plan",
        dueDate: "2026-02-12",
        amount: 60000,
        paid: true,
      },
      {
        id: "m5",
        name: "MVP Build",
        dueDate: "2026-04-22",
        amount: 120000,
        paid: true,
      },
      {
        id: "m6",
        name: "UAT + Soft Launch",
        dueDate: "2026-05-30",
        amount: 105000,
        paid: false,
      },
    ],
    tasks: [
      {
        id: "t6",
        title: "Telehealth video integration",
        status: "in_progress",
        assignee: "u5",
        priority: "high",
        estimateHours: 32,
        loggedHours: 22,
      },
      {
        id: "t7",
        title: "QA matrix for appointment flows",
        status: "in_review",
        assignee: "u6",
        priority: "high",
        estimateHours: 12,
        loggedHours: 11,
      },
      {
        id: "t8",
        title: "Accessibility audit (WCAG 2.2 AA)",
        status: "in_progress",
        assignee: "u3",
        priority: "medium",
        estimateHours: 16,
        loggedHours: 4,
      },
      {
        id: "t9",
        title: "Audit log export endpoint",
        status: "done",
        assignee: "u4",
        priority: "high",
        estimateHours: 8,
        loggedHours: 7,
      },
    ],
  },
  {
    id: "p3",
    name: "Beacon — Onboarding Flow",
    clientId: "c5",
    status: "discovery",
    startDate: "2026-04-22",
    targetDate: "2026-07-10",
    progress: 12,
    budget: 92000,
    spent: 8400,
    margin: 38,
    team: ["u2", "u3"],
    pm: "u2",
    description:
      "End-to-end onboarding redesign with KYC, plaid integration, and behavioral analytics.",
    scopeCreepPct: 0,
    onTime: true,
    milestones: [
      {
        id: "m7",
        name: "Research Synthesis",
        dueDate: "2026-05-13",
        amount: 22000,
        paid: false,
      },
      {
        id: "m8",
        name: "Prototype Approved",
        dueDate: "2026-06-10",
        amount: 30000,
        paid: false,
      },
      {
        id: "m9",
        name: "Final Handoff",
        dueDate: "2026-07-10",
        amount: 40000,
        paid: false,
      },
    ],
    tasks: [
      {
        id: "t10",
        title: "Stakeholder interviews",
        status: "in_progress",
        assignee: "u2",
        priority: "high",
        estimateHours: 12,
        loggedHours: 6,
      },
      {
        id: "t11",
        title: "Competitive teardown",
        status: "in_review",
        assignee: "u3",
        priority: "medium",
        estimateHours: 8,
        loggedHours: 7,
      },
    ],
  },
  {
    id: "p4",
    name: "Civica — Permits Portal",
    clientId: "c7",
    status: "uat",
    startDate: "2025-11-04",
    targetDate: "2026-05-15",
    progress: 92,
    budget: 240000,
    spent: 226800,
    margin: 14,
    team: ["u2", "u4", "u5", "u6"],
    pm: "u2",
    description:
      "Citizen-facing permits portal with payments, document upload, and case tracking.",
    scopeCreepPct: 12.4,
    onTime: false,
    milestones: [
      {
        id: "m10",
        name: "Stage Sign-off",
        dueDate: "2026-04-02",
        amount: 80000,
        paid: true,
      },
      {
        id: "m11",
        name: "UAT Sign-off",
        dueDate: "2026-05-09",
        amount: 70000,
        paid: false,
      },
      {
        id: "m12",
        name: "Production Cutover",
        dueDate: "2026-05-15",
        amount: 90000,
        paid: false,
      },
    ],
    tasks: [
      {
        id: "t12",
        title: "Resolve critical UAT defects",
        status: "in_progress",
        assignee: "u4",
        priority: "high",
        estimateHours: 20,
        loggedHours: 14,
      },
      {
        id: "t13",
        title: "Section 508 compliance pass",
        status: "in_review",
        assignee: "u3",
        priority: "high",
        estimateHours: 12,
        loggedHours: 12,
      },
      {
        id: "t14",
        title: "Production runbook",
        status: "backlog",
        assignee: "u5",
        priority: "medium",
        estimateHours: 8,
        loggedHours: 0,
      },
    ],
  },
  {
    id: "p5",
    name: "Lumen — Marketing Site",
    clientId: "c4",
    status: "discovery",
    startDate: "2026-04-29",
    targetDate: "2026-07-30",
    progress: 4,
    budget: 68000,
    spent: 1200,
    margin: 41,
    team: ["u2", "u3", "u4"],
    pm: "u2",
    description:
      "New marketing site with case study CMS and motion-rich landing experiences.",
    scopeCreepPct: 0,
    onTime: true,
    milestones: [
      {
        id: "m13",
        name: "Kickoff & SOW Signed",
        dueDate: "2026-05-02",
        amount: 17000,
        paid: false,
      },
      {
        id: "m14",
        name: "Design System",
        dueDate: "2026-06-12",
        amount: 21000,
        paid: false,
      },
      {
        id: "m15",
        name: "Launch",
        dueDate: "2026-07-30",
        amount: 30000,
        paid: false,
      },
    ],
    tasks: [],
  },
];

export const projectById = (id: string) => projects.find((p) => p.id === id);

export const designReviews: DesignReview[] = [
  {
    id: "d1",
    projectId: "p1",
    title: "Northwind — Homepage Hero v3",
    thumbnail: "northwind-hero",
    status: "pending",
    version: 3,
    reviewers: ["Renee Park", "Maya Chen"],
    dueDate: "2026-05-04",
    comments: [
      {
        id: "dc1",
        author: "Renee Park",
        message:
          "The hero copy feels too corporate — can we try something warmer that nods to the roastery roots?",
        timestamp: "2 hours ago",
        resolved: false,
        pinX: 28,
        pinY: 32,
      },
      {
        id: "dc2",
        author: "Priya Shah",
        message:
          "Switched the secondary CTA to outline so it doesn't compete. Pushed v3 with updated grain texture.",
        timestamp: "1 hour ago",
        resolved: false,
        pinX: 64,
        pinY: 58,
      },
      {
        id: "dc3",
        author: "Maya Chen",
        message: "Love the type pairing. Approving once Renee's note is in.",
        timestamp: "20 min ago",
        resolved: false,
      },
    ],
  },
  {
    id: "d2",
    projectId: "p2",
    title: "Helio — Appointments Empty State",
    thumbnail: "helio-empty",
    status: "approved",
    version: 2,
    reviewers: ["Adam Field", "Diego Alvarez"],
    dueDate: "2026-04-29",
    comments: [
      {
        id: "dc4",
        author: "Adam Field",
        message: "Approved. The illustration tone matches the rest of the portal.",
        timestamp: "yesterday",
        resolved: true,
      },
    ],
  },
  {
    id: "d3",
    projectId: "p4",
    title: "Civica — Document Upload Modal",
    thumbnail: "civica-upload",
    status: "changes_requested",
    version: 4,
    reviewers: ["Owen Hart"],
    dueDate: "2026-05-02",
    comments: [
      {
        id: "dc5",
        author: "Owen Hart",
        message:
          "We need to call out the 25MB limit before upload, not after the failure state.",
        timestamp: "3 hours ago",
        resolved: false,
        pinX: 50,
        pinY: 42,
      },
      {
        id: "dc6",
        author: "Owen Hart",
        message:
          "Add a 'last saved' indicator so applicants know progress is preserved.",
        timestamp: "3 hours ago",
        resolved: false,
        pinX: 78,
        pinY: 18,
      },
    ],
  },
];

export const invoices: Invoice[] = [
  {
    id: "i1",
    number: "INV-2026-041",
    clientId: "c1",
    projectId: "p1",
    milestoneId: "m1",
    amount: 28000,
    status: "paid",
    issuedDate: "2026-04-03",
    dueDate: "2026-04-18",
    paidDate: "2026-04-12",
  },
  {
    id: "i2",
    number: "INV-2026-052",
    clientId: "c2",
    projectId: "p2",
    milestoneId: "m4",
    amount: 60000,
    status: "paid",
    issuedDate: "2026-02-13",
    dueDate: "2026-02-28",
    paidDate: "2026-02-25",
  },
  {
    id: "i3",
    number: "INV-2026-053",
    clientId: "c2",
    projectId: "p2",
    milestoneId: "m5",
    amount: 120000,
    status: "paid",
    issuedDate: "2026-04-23",
    dueDate: "2026-05-08",
    paidDate: "2026-05-01",
  },
  {
    id: "i4",
    number: "INV-2026-061",
    clientId: "c7",
    projectId: "p4",
    milestoneId: "m10",
    amount: 80000,
    status: "paid",
    issuedDate: "2026-04-03",
    dueDate: "2026-04-18",
    paidDate: "2026-04-21",
  },
  {
    id: "i5",
    number: "INV-2026-064",
    clientId: "c2",
    projectId: "p2",
    amount: 8400,
    status: "sent",
    issuedDate: "2026-04-26",
    dueDate: "2026-05-11",
  },
  {
    id: "i6",
    number: "INV-2026-067",
    clientId: "c7",
    projectId: "p4",
    amount: 14200,
    status: "overdue",
    issuedDate: "2026-04-08",
    dueDate: "2026-04-23",
  },
  {
    id: "i7",
    number: "INV-2026-070",
    clientId: "c4",
    projectId: "p5",
    milestoneId: "m13",
    amount: 17000,
    status: "draft",
    issuedDate: "2026-05-01",
    dueDate: "2026-05-16",
  },
];

export const kpis = {
  approvalCycleDays: 2.4,
  scopeCreepPct: 4.2,
  onTimeMilestonesPct: 91,
  daysSalesOutstanding: 22,
  utilizationPct: 78,
  marginPct: 28,
  activeProjects: projects.filter((p) => p.status !== "launched").length,
  outstandingAR: invoices
    .filter((i) => i.status === "sent" || i.status === "overdue")
    .reduce((s, i) => s + i.amount, 0),
};
